### ISSUE TITLE
[🎹 Inside Test] Post-trial, accuracy error-animation in tempo should play at level tempo (not slower), and color code by mistake kind

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#61]
there are two issues regarding this feature:
1) it should be shown in the same tempo that is being enforced on this level, and not slower. it could be confusing speed-wise

2) it should show only the acc errors, and not rhythm errors. alternatively, we can show the rhythm errors in a different colour (blue, perhaps?). if so, this colour should be shown on ev very rhythm error animation as well. what's you take on the matter?

**Comment by giladbarnea** [comment]
> 1. it should be shown in the same tempo that is being enforced on this level, and not slower. it could be confusing speed-wise

In issue #57, you wrote:
> it currently plays the error animations with the slow-down factor, which is not supposed to happen in tempo mode.

So should there be NO slowing down whatsoever, or should there be slowing down according to that level's tempo setting?
Additionally, are you also talking about rhythm errors in tempo mode? I'm asking because the original title of the issue was "acc error post animation in tempo mode".

> 2. it should show only the acc errors, and not rhythm errors. alternatively, we can show the rhythm errors in a different colour (blue, perhaps?). if so, this colour should be shown on ev very rhythm error animation as well. what's you take on the matter?

I think marking different kinds of mistakes with different colors is a good choice.
I'm not sure "red / blue" distinction is ideal, I'll ask Maurann. Pretty sure she already suggested something about it. 
After thinking about it, I agree that rhythm errors should **not** be displayed if the user had accuracy errors in tempo mode. Only the accuracy mistakes should be shown. This is because it's "a whole different level of bad" to get accuracy wrong when tested on tempo.

**Comment by ShacharGal** [comment]
Coolness

**Comment by giladbarnea** [comment]
Contents were summarized in [Demoes project](https://github.com/idotavorslab/PYANO/projects/1#card-21108156)
