### ISSUE TITLE
simultaneousness errors should count as rhythm, not accuracy

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#72]
when playing with both hands, if notes that should be simultaneous are played one after the other but not exactly together, it should count as a rhythm error, and not accuracy (because the notes are right, it's just not played the right way).
this should be sensitive to both possible orders-lower note before higher and vice Versa.

point for thought - will and how this be effected by the rhythm deviation factor?

**Comment by ShacharGal** [comment]
importance for this issue is very high - for some reason I can't add labels.

**Comment by giladbarnea** [comment]
Do you remember what was the config? Any other details? (what level, trial etc). The actual trial file would save me hours.
Would help us both if you sent me the config.json file (not a verbal description of the config) and posted a screenshot. Since our bugs become more and more elusive (the more complex the app becomes...) I'll need more info from you
